name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Sync previous build
        run: |
          mkdir dist
          git fetch origin dist --depth 1
          git worktree add dist origin/dist

      - name: Install deps 🔧
        run: npm install

      - name: Build 🔧
        run: |
          npm run build:lejeu
          npm run rollup:lejeu

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: dist # The branch the action should deploy to.
          # single-commit: true
          folder: dist # The folder the action should deploy.
